name: app

type: php:7.2
build:
    flavor: composer

variables:
    env:
        APP_ENV: 'prod'
        APP_DEBUG: 0

relationships:
    database: "mysqldb:mysql"

dependencies:
    nodejs:
        yarn: "*"

# The hooks that will be performed when the package is deployed.
hooks:
    build: |
        bin/console assets:install --no-debug
        bin/console cache:clear
        bin/console assets:install --symlink --relative public
        bin/console cache:clear
        bin/console doctrine:schema:drop --force
        bin/console doctrine:schema:update --force
        bin/console doctrine:fixtures:load --no-interaction
    deploy: |


# The size of the persistent disk of the application (in MB).
disk: 2048

# The mounts that will be performed when the package is deployed.
mounts:
    "/var/cache": "shared:files/cache"
    "/var/log": "shared:files/log"
    "/var/sessions": "shared:files/sessions"
    "/var/app.db": "shared:files/app.db"

# The configuration of app when it is exposed to the web.
web:
    locations:
        "/":
            # The public directory of the app, relative to its root.
            root: "public"
            # The front-controller script to send non-static requests to.
            passthru: "/index.php"