version: '3.4'
services:
  db:
    image: postgres:10.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
  web:
    image: abiosoft/caddy:php
    ports:
      - 80:80
      - 2015:2015
      - 443:443
    volumes:
      - ./:/srv
      - ./Caddyfile:/etc/Caddyfile
      - ~/.caddy:/root/.caddy
  node:
    image: node:9
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
